# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"notnone": "00_core.ipynb",
         "lmap": "00_core.ipynb",
         "get_files": "00_core.ipynb",
         "get_image_files": "00_core.ipynb",
         "image_extensions": "00_core.ipynb",
         "open_img": "02_data.core.ipynb",
         "show_img": "02_data.core.ipynb",
         "grid": "02_data.core.ipynb",
         "Mask": "04_data.annotations.ipynb",
         "RLE": "04_data.annotations.ipynb",
         "Polygon": "04_data.annotations.ipynb",
         "BBox": "04_data.annotations.ipynb",
         "ImageInfo": "04_data.annotations.ipynb",
         "Instance": "04_data.annotations.ipynb",
         "Annotation": "04_data.annotations.ipynb",
         "Record": "04_data.annotations.ipynb",
         "ImageParser": "04_data.annotations.ipynb",
         "AnnotationParser": "04_data.annotations.ipynb",
         "DataParser": "04_data.annotations.ipynb",
         "COCOImageParser": "04_data.annotations.ipynb",
         "COCOAnnotationParser": "04_data.annotations.ipynb",
         "COCOParser": "04_data.annotations.ipynb",
         "show_record": "04_data.annotations.ipynb"}

modules = ["core.py",
           "data/core.py",
           "data/annotation.py"]

doc_url = "https://lgvaz.github.io/mantisshrimp/"

git_url = "https://github.com/lgvaz/mantisshrimp/tree/master/"

def custom_doc_links(name): return None
