# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00b_lightning_core.ipynb (unless otherwise specified).

__all__ = ['old_lrfinder_plot']

# Cell
from .imports import *
from .core import *
from pytorch_lightning.trainer.lr_finder import _LRFinder

# Cell
old_lrfinder_plot = _LRFinder.plot
@patch
def plot(self:_LRFinder, skip_start=5, skip_end=5, suggest=False, show=False):
    old = self.results
    self.results = {k:v[skip_start:-skip_end] for k,v in old.items()}
    res = old_lrfinder_plot(self, suggest=suggest, show=show)
    self.results = old
    return res