name: Check Formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==19.10b0

    - name: Check Black formatting
      run: black --check .
