name: Build and Publish GPU Docker
on:
  push:
    branches:
      - docker_deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: lgvaz/icevision@docker_deploy
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: lgvaz/icevision
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tags: "latest"
