name: Build and Publish GPU Docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env_name: ["icevision-stable", "icevision-dev"]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            ENV_NAME=${{env_name}}
          file: Dockerfile
          push: false
