name: Build and Publish GPU Docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ["dev", "prod"]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Get release version
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        id: release
        run: echo ::set-output name=tags::$(echo ${GITHUB_REF##*/})

      - uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          build-args: |
            BUILD=${{ matrix.build }}
          file: Dockerfile
          push: true
          tags: icevision/icevision:${{ steps.release.output.tags }},icevision/icevision:latest

      - uses: docker/build-push-action@v2
        if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event_name != 'release' && !startsWith(github.ref, 'refs/tags/')
        with:
          build-args: |
            BUILD=${{ matrix.build }}
          file: Dockerfile
          push: false
