name: Install Package

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pkg-check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create package
        run: |
          python setup.py sdist
      - name: Check package
        run: |
          pip install twine==1.13.0
          twine check dist/*
          python setup.py clean

  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # max-parallel: 6
      matrix:
        os: [ubuntu-20.04] # , windows-2019] 
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create package
        run: |
          python setup.py sdist
      - name: Install package
        run: |
          pip install dist/*
          cd .. & python -c "import mantisshrimp as ms; print(ms.__version__)"
          deactivate ; rm -rf vEnv